// generators/app/templates/_client_vue/App.vue
<template>
  <div class="app">
    hello {{ username }}
  </div>
</template>

<script>
export default {
  data() {
    return {
      username: '...'
    }
  },
  created() {
    f_Request('/getusername', {})
      .then(data => {
        if (!data) return
        this.username = data.username
      })
  }
}
</script>

<style lang="scss" scoped>
.app {
  
}
</style>

// generators/app/templates/_client_react/App.jsx
import React, { Component } from 'react'
import {
  BrowserRouter as Router,
  Route,
  NavLink
} from 'react-router-dom'

class App extends Component {
  constructor() {
    super()
    this.state = {}
  }
  componentWillMount() {
    f_Request('/getusername', {})
      .then(data => {
        if (!data) return
        this.setState({
          username: data.username
        })
      })
  }

  render() {
    return (
      <div>
        {this.state.username}, hello world!
      </div>
    )
  }
}

export default App
